# Numpy
---

# Quiz 1
1.จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [1]:
import numpy as np

In [2]:
#vector
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#mattrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Quiz 2
2.จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [4]:
#vector
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
#matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Quiz 3
3. จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [6]:
num = np.random.uniform(10,99,20)
num**2

array([7654.10556776, 1864.30793378,  783.72494973, 3802.82167799,
       7133.42219573, 8867.09818651, 7091.4982565 , 5384.58744269,
       1265.36611792, 2403.57198277, 1963.27795208,  596.35036616,
       3949.69848856, 7054.0396163 ,  147.62234454, 3632.24179197,
       4501.8541971 , 5949.1785326 , 1337.67554305, 3274.92674141])

# Quiz 4
4. ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension

In [9]:
import random
x =np.random.uniform(10,99,20)
num2 = list(x)
num3 = [i**2 for i in num2]
print(num3)

[5838.107506481321, 8174.783045520185, 3076.7506263132564, 250.69431222891671, 1616.4594665394768, 1109.0514307757765, 6270.1955989427, 5371.482214549104, 3488.5656513382864, 4437.940250862074, 9045.061529757924, 8457.90132339322, 359.7425847581359, 124.56940925543599, 3013.6138198482518, 3432.874861841413, 5386.469244304883, 1219.938250230903, 3305.454520458546, 4181.81032414352]


# Quiz 5
5. นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

In [10]:
import time
#Solution Numpy
time1 = time.time()
num = np.random.uniform(10,99,20)
num**2
time2 = time.time()
time_array = time2 - time1
print(time_array)

0.0


In [11]:
# Solution List Comprehension
time1 = time.time()
x =np.random.uniform(10,99,20)
num2 = list(x)
num3 = [i**2 for i in num2]
time2 = time.time()
time_list = time2 - time1
print(time_list)

0.0


# Quiz 6
6 .จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000  

In [12]:
a = np.arange(10,1001)
a

array([  10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99,  100,  101,  102,  103,  104,  105,  106,  107,  108,
        109,  110,  111,  112,  113,  114,  115,  116,  117,  118,  119,
        120,  121,  122,  123,  124,  125,  126,  127,  128,  129,  130,
        131,  132,  133,  134,  135,  136,  137,  138,  139,  140,  141,
        142,  143,  144,  145,  146,  147,  148,  149,  150,  151,  152,
        153,  154,  155,  156,  157,  158,  159,  1

# Quiz 7
7. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000 

In [13]:
quiz_7 = np.arange(10,2001,2)
quiz_7

array([  10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98,  100,  102,  104,  106,  108,  110,  112,  114,  116,  118,
        120,  122,  124,  126,  128,  130,  132,  134,  136,  138,  140,
        142,  144,  146,  148,  150,  152,  154,  156,  158,  160,  162,
        164,  166,  168,  170,  172,  174,  176,  178,  180,  182,  184,
        186,  188,  190,  192,  194,  196,  198,  200,  202,  204,  206,
        208,  210,  212,  214,  216,  218,  220,  222,  224,  226,  228,
        230,  232,  234,  236,  238,  240,  242,  244,  246,  248,  250,
        252,  254,  256,  258,  260,  262,  264,  266,  268,  270,  272,
        274,  276,  278,  280,  282,  284,  286,  288,  290,  292,  294,
        296,  298,  300,  302,  304,  306,  308,  3

# Quiz 8
8. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

In [14]:
quiz_8 = np.arange(13,900,2)
quiz_8

array([ 13,  15,  17,  19,  21,  23,  25,  27,  29,  31,  33,  35,  37,
        39,  41,  43,  45,  47,  49,  51,  53,  55,  57,  59,  61,  63,
        65,  67,  69,  71,  73,  75,  77,  79,  81,  83,  85,  87,  89,
        91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111, 113, 115,
       117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141,
       143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
       169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193,
       195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219,
       221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245,
       247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271,
       273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297,
       299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323,
       325, 327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349,
       351, 353, 355, 357, 359, 361, 363, 365, 367, 369, 371, 37

# Quiz 9
9. จงสร้าง identity matrix แบบ 4x4

In [15]:
quiz_9 = np.eye(4)
quiz_9

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Quiz 10
10. จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

In [20]:
quiz_10 = np.linspace(5,25,100)
quiz_10[2] - quiz_10[1]

0.20202020202020154

# Quiz 11
11. จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

In [21]:
quiz_11 = np.random.rand(1)
quiz_11

array([0.68051714])

# Quiz 12
12. จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose  

In [22]:
quiz_12 = np.random.randint(50,101,(4,4))
quiz_12.T

array([[64, 93, 90, 66],
       [81, 97, 78, 92],
       [53, 56, 64, 73],
       [66, 89, 59, 68]])

# Quiz 17
17. จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา
   
    array ([[ 1,  2,  3,  4,  5], 
           [ 6,  7,  8,  9, 10], 
           [11, 12, 13, 14, 15], 
           [16, 17, 18, 19, 20], 
           [21, 22, 23, 24, 25]])

In [23]:
arr = np.arange(1,26,)
arr = arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Quiz 13 - 16

In [26]:
# 13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14 
arr[1:3 , 2:4]

array([[ 8,  9],
       [13, 14]])

In [27]:
# 14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20
arr[3 , 2:]

array([18, 19, 20])

In [28]:
# 15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22
arr[3: , :2]

array([[16, 17],
       [21, 22]])

In [29]:
# 16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3
arr[2]

array([11, 12, 13, 14, 15])

# Quiz 18
18. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า 50 และปริ้นออกมา

In [30]:
quiz_18 = np.random.randint(10,101,(5,5))
quiz_18

array([[24, 71, 71, 51, 69],
       [13, 32, 31, 32, 52],
       [79, 59, 33, 77, 26],
       [72, 68, 71, 73, 99],
       [48, 44, 24, 48, 38]])

In [31]:
quiz_18[quiz_18 > 50]

array([71, 71, 51, 69, 52, 79, 59, 77, 72, 68, 71, 73, 99])

# Quiz 19
19. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่ามากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

In [32]:
quiz_19 = np.random.randint(10,101,(5,5))
quiz_19

array([[ 93,  68,  73,  72,  65],
       [ 40,  35,  75,  31,  81],
       [ 62,  76, 100,  26,  90],
       [ 25,  61,  50,  33,  66],
       [ 49,  27,  15,  97,  36]])

In [33]:
a40 = quiz_19[quiz_19 > 40]
list(a40)

[93, 68, 73, 72, 65, 75, 81, 62, 76, 100, 90, 61, 50, 66, 49, 97]

# Quiz 20
20. เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)

In [34]:
list20 = []
for i in range(9):
    number = int(input("กรุณาป้อนตัวเลข"))
    list20.append(number)
arr20 = np.array(list20) 
arr20new = arr20.reshape(3,3)
print(arr20new)

กรุณาป้อนตัวเลข 1
กรุณาป้อนตัวเลข 2
กรุณาป้อนตัวเลข 3
กรุณาป้อนตัวเลข 4
กรุณาป้อนตัวเลข 5
กรุณาป้อนตัวเลข 6
กรุณาป้อนตัวเลข 7
กรุณาป้อนตัวเลข 8
กรุณาป้อนตัวเลข 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
arr20new.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
arr20new[2,2]

9